# Generated by Django 2.2 on 2019-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='password1',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
