# Generated by Django 2.2 on 2019-06-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_registrations_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registrations',
        ),
    ]
