# Generated by Django 2.2 on 2019-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190605_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='Firstname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='Lastname',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
