# Generated by Django 2.2 on 2019-06-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190606_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Lastname',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
